// Package catch offers a list of functions to use in conjunction with try.Catch() to handle panics.
package catch
