package exceptions

func Throw(exception Exception) {
	panic(exception)
}
